spring:
  main:
    banner-mode: "off"
    web-environment: false
    
logging:
  level:
    root: INFO
  pattern:
    console: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}) %clr(%-5p) %clr(---) %clr(%m){faint}%n"

  file: logs/pr-populator-tool.log

pr-populator:
  credentials-file-path: /credentials.json
  diff-file:
    path: 
    filename:
      prefix: diff
      date-format: MMMdd-yyyy-hhmmss
  jira:
    jql-filter-query: issuetype ='Faster Story' AND 'Target Quarter' = <quarter>
    instance-url: https://jira.devfactory.com
    credentials:
      userName: 
      password: 
    rest-api-path: /rest/api/2

  google-config:
    spreadsheetPRSheet:
      id: 1jJiODmRFDES_FIbON2uQsqlC9LIsG2lfKCR9lfOwRQM ## Full URL: https://docs.google.com/spreadsheets/d/1jJiODmRFDES_FIbON2uQsqlC9LIsG2lfKCR9lfOwRQM/edit#gid=0
      name: PullRequests
      data-range: PullRequests!A1:F
      prIdColumnName: PR ID
      prUrlColumnName: PR URL
      jiraIdColumnName: JIRA ID
      productColumnName: Product
      quarterColumnName: Quarter
      yearColumnName: Year
      maxEmptySequencialRows: 10
    spreadsheetProductToRepoSheet:
      id: 1jJiODmRFDES_FIbON2uQsqlC9LIsG2lfKCR9lfOwRQM ## Full URL: https://docs.google.com/spreadsheets/d/1jJiODmRFDES_FIbON2uQsqlC9LIsG2lfKCR9lfOwRQM/edit#gid=1006919491
      name: RepoToProductMapping
      data-range: RepoToProductMapping!A1:B
      productColumnName: Product
      repositoryUrlColumnName: Repository URL
      maxEmptySequencialRows: 10
  git-hub:
    oauth-token: 
    org-name: trilogy-group
    team-url: https://github.com/orgs/trilogy-group/teams/faster-developers
    api-request-limit: 1500
    depth-scan: 90
    api-base-path: https://api.github.com
    second-between-retries: 5
    max-retries: 5